name: testing

# cuando ocurren los siguientes eventos
on:
  # cuando hay push en la branch main
  push:
    branches:
      - main

# Un workflow se compone de uno o más jobs que pueden correr en serie o paralelo
jobs:
  # This workflow contains a single job called "compile-sketches"
  markdown-lint:
    # corre en una máquina ubuntu
    runs-on: ubuntu-latest

    # pasos que son parte del job
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: hacer lint
      uses: piruetasxyz/filename-fixer@v0.0.1-alpha
      